# Generated by Django 5.0.6 on 2024-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
