# Generated by Django 5.0.6 on 2024-06-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_round_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.round'),
        ),
    ]
