# Generated by Django 5.0.6 on 2024-06-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_card_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playercard', to='game.card'),
        ),
    ]
